#! /bin/sh

##Autostart
lxpolkit &
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
picom &
nm-applet &

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7

##Main settings
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config focus_follows_pointer true


##Color theme (based on Adapta Dark colors)
bspc config focused_border_color "#00bcd4"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"

#Window rules
bspc rule -a "SimpleScreenRecorder" state=floating
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Yandex-browser" desktop=^2
bspc rule -a "Nano" desktop=^3
bspc rule -a "Spotify" desktop=^5
bspc rule -a "Gimp" desktop=^6
bspc rule -a "Telegram-desktop" desktop=^4
bspc rule -a "discord" desktop=^4
bspc rule -a "cmus" desktop=^5
